### ISSUE TITLE
Asking for some clarification

### ISSUE THREAD

**Issue by ghost** [doronbehar/invidious-redirect#1] opened 2019-05-26 13:09 UTC
Hi,

I'm running _Invidious Redirect_ 1.13 / Firefox 67.0 (x64) / Windows 7 (x64).
I've set both instances of Individious in the extension's Options page.

I'm not sure to understand the following:

**1-** AMO page states:

> Redirects YouTube requests to an alternative frontend of your choice, defaults to invidio.us. The settings page allows you to configure a specific Invidious instance to which the request will be redirected.

Which corresponds to the extension's option:
`Instance of Invidious when redirecting`

Does this concern requests to a YouTube link performed from the YouTube site itself?
If so, this doesn't work here: when on the YouTube site videos are opened in YouTube.

**2-** AMO page states:

>You can also use a different instance for embeddable content and normal tabs.

Which corresponds to the extension's option:
`Instance of Invidious to use when replacing iframe (embeds)`

Embeddable content, I know, but what does _normal tabs_ mean?

**3**- Embeddable content, that is Youtube videos called from a site which is not YouTube.com, is perfectly handled by _Invidious Redirect_. But YouTube videos called from YouTube are played on YouTube, not on the Invidious instance chosen in the extension's Options: NOTE: I prefer that, but not sure this is intended by _Individious Redirect_

**4-** Invidious instances offer the possibility to view a running video on YouTube (_Watch on YouTube_) :  unfortunately this is impossible with _Invidious Redirect_ because the extension redirects always to the chosen Invidious instance.

**5-** My opinion:

a) Invidious Redirect should consider two exceptions: YouTube.com and the chosen Invidious instance site. (for the latter, if applicable considering point **1-** above)

b) A toolbar button as a general on/off switch for _Invidious Redirect_ would be welcomed.

Many thanks!

**Comment by doronbehar** [comment] 2019-05-26 15:34
Hello @StanGets (Cool username BTW),

Thanks for your comments, they are greatly appreciated. I'll address each point:

1. Technically, I'd expect this to redirect requests inside YouTube as well but I guess not? How did you manage to even enter YouTube.com when the extension is active?

2. 'Normal tabs' means: Normal links to open videos or whatever in the same tab as you are on or new tabs, I hope that's clear. Do you have a better description? If so, I'd be happy to hear and possibly update the description.

3. Again - 'YouTube Videos from inside YouTube'? Please give me instructions to reproduce this situation because I guess this means there are some wholes in the protection this extension attempts to give the user from malicious youtube.com .

4. Yea, I know.. Well, there is no elegant way I can think of to overcome that unless a 'toolbar button as a general on/off' would be implemented, as you suggested in point 5, I'll note that.

5. **a**) I believe this impossible using the API used by the extension i.e [request blocking](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/BlockingResponse). You see, we want to block every request to YouTube - if we'll not block requests to YouTube on youtube.com, that would destruct the whole purpose of the extension (besides embeds). **b**) Addressed in 4.

**Comment by ghost** [comment] 2019-05-26 16:03
Hello @doronbehar and thanks for replying so completely and quickly.

1- OK, I get it. The extension aims at redirecting all links to YouTube, including youtube.com, and I shouldn't have been able to access youtube.com to start with, which is why links on youtube.com weren't redirected. Well, I did access the homepage. With `https://www.youtube.com/` I open youtube.com, but with `https://www.youtube.com/watch?v=[xyz]` the link is correctly redirected, as well as `https://www.youtube.com/channel/[xyz]` ... but not ` https://www.youtube.com/user/[xyz]` - Odd.

2- I understand better what normal tabs means. I was not criticizing the denomination, given I didn't understand what it corresponded to. Now the basic user understands!

3- Goes with Point (1). I happened to have landed on youtube.com and from there on links on that site opened on that site, not redirected. But as I understand your answer, I shouldn't have landed on Youtube.com, which should have been redirected.

4- Isn't it possible to just consider the chosen Invidious instances as exceptions for the extension, like userscripts do? I guess not given your answer. I'm not a coder, nor a cooker, but i like good food!

5- Your answer answers as well my Point 4-

OK. Clarified in my small brains. I see better.

So, the only problem as I understand it now is that I managed to enter youtube.com (home-page) when theoretically the extension should have handled that as well (sounds like a security scenario!), as you mention it:

> You see, we want to block every request to YouTube

P.S. I loved, love and always will love _The Sound_, alias _Stan Getz_ :=)

**Comment by doronbehar** [comment] 2019-05-27 13:18
> Isn't it possible to just consider the chosen Invidious instances as exceptions for the extension, like userscripts do?

Not with the API method I chose to use which is the most efficient one because it completely blocks the requests before they are even made. From what I've found out when reading it's documentation, this API method can't be aware of the URL of the window from which the request was made. Userscripts work differently and in order to achieve the goal of this extension, they would work less efficiently and would be more complicated to write and maintain. This is because from what I know, they usually manipulate the HTML of a web page and they don't access the actual requests browser sends.

An on/off toggle button on toolbar could certainly be useful. Allow me to close this issue as it was mostly a discussion. Please open a new issue just only with this feature request if you still want it.

**Closed as completed by doronbehar** 2019-05-27 13:18 UTC
